#!/bin/bash
set -e -x

repo=ware
if [ -f .repo ]; then
    repo="$(cat .repo)"
fi

rm -rf results
mkdir -p results

opts=()
if [ -f .dist ]; then
    opts+=(-r "$(cat .dist)")
fi
opts+=(--buildsrpm --spec *.spec --sources SOURCES --resultdir results)
mock "${opts[@]}"

pigz results/*.log

opts=(--nowait)
if [ -f .exclude-chroot ]; then
    while read o; do
        opts+=(-r "$o")
    done < <(copr-cli list maage | sed -rn '/^Name: '"$repo"'$/,/^$/{/maage\/'"$repo"'/{s/^ *//;s/:.*//;p}}' | fgrep -v -f .exclude-chroot)
fi
exec copr-cli build "${opts[@]}" "$@" "$repo" results/*.src.rpm
